/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/reset-password`; params?: Router.UnknownInputParams; } | { pathname: `/subscription`; params?: Router.UnknownInputParams; } | { pathname: `/leaderboard`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/favorites` | `/favorites`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/profile` | `/profile`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/watching` | `/watching`; params?: Router.UnknownInputParams; } | { pathname: `/lists/create`; params?: Router.UnknownInputParams; } | { pathname: `/lists`; params?: Router.UnknownInputParams; } | { pathname: `/settings/help`; params?: Router.UnknownInputParams; } | { pathname: `/settings/language`; params?: Router.UnknownInputParams; } | { pathname: `/settings/privacy`; params?: Router.UnknownInputParams; } | { pathname: `/settings/terms`; params?: Router.UnknownInputParams; } | { pathname: `/+not-found`, params: Router.UnknownInputParams & {  } } | { pathname: `/anime/[id]`, params: Router.UnknownInputParams & { id: string | number; } } | { pathname: `/lists/[id]`, params: Router.UnknownInputParams & { id: string | number; } } | { pathname: `/users/[id]`, params: Router.UnknownInputParams & { id: string | number; } };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/`; params?: Router.UnknownOutputParams; } | { pathname: `/reset-password`; params?: Router.UnknownOutputParams; } | { pathname: `/subscription`; params?: Router.UnknownOutputParams; } | { pathname: `/leaderboard`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/favorites` | `/favorites`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/profile` | `/profile`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/watching` | `/watching`; params?: Router.UnknownOutputParams; } | { pathname: `/lists/create`; params?: Router.UnknownOutputParams; } | { pathname: `/lists`; params?: Router.UnknownOutputParams; } | { pathname: `/settings/help`; params?: Router.UnknownOutputParams; } | { pathname: `/settings/language`; params?: Router.UnknownOutputParams; } | { pathname: `/settings/privacy`; params?: Router.UnknownOutputParams; } | { pathname: `/settings/terms`; params?: Router.UnknownOutputParams; } | { pathname: `/+not-found`, params: Router.UnknownOutputParams & {  } } | { pathname: `/anime/[id]`, params: Router.UnknownOutputParams & { id: string; } } | { pathname: `/lists/[id]`, params: Router.UnknownOutputParams & { id: string; } } | { pathname: `/users/[id]`, params: Router.UnknownOutputParams & { id: string; } };
      href: Router.RelativePathString | Router.ExternalPathString | `/${`?${string}` | `#${string}` | ''}` | `/reset-password${`?${string}` | `#${string}` | ''}` | `/subscription${`?${string}` | `#${string}` | ''}` | `/leaderboard${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/favorites${`?${string}` | `#${string}` | ''}` | `/favorites${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/profile${`?${string}` | `#${string}` | ''}` | `/profile${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/watching${`?${string}` | `#${string}` | ''}` | `/watching${`?${string}` | `#${string}` | ''}` | `/lists/create${`?${string}` | `#${string}` | ''}` | `/lists${`?${string}` | `#${string}` | ''}` | `/settings/help${`?${string}` | `#${string}` | ''}` | `/settings/language${`?${string}` | `#${string}` | ''}` | `/settings/privacy${`?${string}` | `#${string}` | ''}` | `/settings/terms${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/reset-password`; params?: Router.UnknownInputParams; } | { pathname: `/subscription`; params?: Router.UnknownInputParams; } | { pathname: `/leaderboard`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/favorites` | `/favorites`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/profile` | `/profile`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/watching` | `/watching`; params?: Router.UnknownInputParams; } | { pathname: `/lists/create`; params?: Router.UnknownInputParams; } | { pathname: `/lists`; params?: Router.UnknownInputParams; } | { pathname: `/settings/help`; params?: Router.UnknownInputParams; } | { pathname: `/settings/language`; params?: Router.UnknownInputParams; } | { pathname: `/settings/privacy`; params?: Router.UnknownInputParams; } | { pathname: `/settings/terms`; params?: Router.UnknownInputParams; } | `/+not-found${`?${string}` | `#${string}` | ''}` | `/anime/${Router.SingleRoutePart<T>}${`?${string}` | `#${string}` | ''}` | `/lists/${Router.SingleRoutePart<T>}${`?${string}` | `#${string}` | ''}` | `/users/${Router.SingleRoutePart<T>}${`?${string}` | `#${string}` | ''}` | { pathname: `/+not-found`, params: Router.UnknownInputParams & {  } } | { pathname: `/anime/[id]`, params: Router.UnknownInputParams & { id: string | number; } } | { pathname: `/lists/[id]`, params: Router.UnknownInputParams & { id: string | number; } } | { pathname: `/users/[id]`, params: Router.UnknownInputParams & { id: string | number; } };
    }
  }
}
